ServerName localhost

<VirtualHost *:80>
    DocumentRoot /var/www/site
    ErrorLog /dev/stderr
    CustomLog /dev/stdout combined

    # PHP 4 en CGI, comme chez Free
    ScriptAlias /php-cgi/ /usr/local/bin/
    Action application/x-httpd-php4 /php-cgi/php
    AddHandler application/x-httpd-php4 .php
    <Directory /usr/local/bin>
        Require all granted
    </Directory>

    <Directory /var/www/site>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
        DirectoryIndex index.php index.html
    </Directory>
</VirtualHost>
